# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/zhou/Desktop/cpu_new/cpu.cache/wt [current_project]
set_property parent.project_path C:/Users/zhou/Desktop/cpu_new/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/rom.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/register.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/mux2_1.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/load_nop.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/singal3.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/singal2.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/singal.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/regfile.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/ram.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/pcc.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/pc.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/MEM_WB.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/instruction.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/IF_ID.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/ID_EX.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/halt.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/EX_MEM.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/count.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/control.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/cacl_pc.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/alu.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/scan.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/frac.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/display.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/choose.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/main.v
  C:/Users/zhou/Desktop/cpu_new/cpu.srcs/sources_1/new/all.v
}
read_xdc C:/Users/zhou/Desktop/cpu_new/cpu.srcs/constrs_1/new/all_xdc.xdc
set_property used_in_implementation false [get_files C:/Users/zhou/Desktop/cpu_new/cpu.srcs/constrs_1/new/all_xdc.xdc]

synth_design -top all -part xc7vx485tffg1157-1
write_checkpoint -noxdef all.dcp
catch { report_utilization -file all_utilization_synth.rpt -pb all_utilization_synth.pb }
